version: "3.7"
services:
  auth:
    build: 
      context: ./auth
      dockerfile: dockerfile
    restart: always
    ports:
      - 8080:8080
    networks:
      - bf-net
    depends_on:
      - mysqldb
  core:
    build: 
      context: ./core
      dockerfile: dockerfile
    restart: always
    ports:
      - 8081:8080
    networks:
      - bf-net
    depends_on:
      - mysqldb
      - redis
  file:
    build: 
      context: ./file
      dockerfile: dockerfile
    restart: always
    ports:
      - 8082:8080
    networks:
      - bf-net
    volumes:
      - storage:/home/storage
  chat:
    build: 
      context: ./chat
      dockerfile: dockerfile
    restart: always
    ports:
      - 8083:4000
    networks:
      - bf-net
    depends_on:
      - mysqldb
  mysqldb:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3307:3306
    networks:
      - bf-net
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
    volumes:
      - mysql:/var/lib/mysql
  redis:
    hostname: redis
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis:/root/redis
    networks:
      - bf-net
    environment:
      - REDIS_PASSWORD=${REDIS_PASS}
  rabbitmq:
    hostname: rabbitmq
    image: rabbitmq:latest
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - queue:/var/lib/rabbitmq
    networks:
      - bf-net
    environment:
      - RABBITMQ_DEFAULT_USER=${MQ_USER}
      - RABBITMQ_DEFAULT_PASS=${MQ_PASS}
networks:
  bf-net:
volumes:
  mysql:
  redis:
  storage:
  queue: