version: "3.7"
services:
  auth:
    build: 
      context: ./auth
      dockerfile: dockerfile
    restart: always
    ports:
      - 8080:8080
    networks:
      - bf-net
    depends_on:
      - mysqldb
  core:
    build: 
      context: ./core
      dockerfile: dockerfile
    restart: always
    ports:
      - 8081:8080
    networks:
      - bf-net
    depends_on:
      - mysqldb
      - redis
  web:
    build: 
      context: ./web
      dockerfile: dockerfile
    restart: always
    ports:
      - 8082:3000
    networks:
      - bf-net
    depends_on:
      - auth
      - core
      - minio
  # chat:
  #   build: 
  #     context: ./chat
  #     dockerfile: dockerfile
  #   restart: always
  #   ports:
  #     - 8083:4000
  #   networks:
  #     - bf-net
  #   depends_on:
  #     - mysqldb
  notif:
    build: 
      context: ./notif
      dockerfile: dockerfile
    restart: always
    networks:
      - bf-net
    depends_on:
      - rabbitmq
  mysqldb:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3307:3306
    networks:
      - bf-net
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
    volumes:
      - mysql:/var/lib/mysql
  redis:
    hostname: redis
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis:/root/redis
    networks:
      - bf-net
    environment:
      - REDIS_PASSWORD=${REDIS_PASS}
  rabbitmq:
    hostname: rabbitmq
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - queue:/var/lib/rabbitmq
    networks:
      - bf-net
    environment:
      - RABBITMQ_DEFAULT_USER=${MQ_USER}
      - RABBITMQ_DEFAULT_PASS=${MQ_PASS}
  minio:
    hostname: minio
    image: minio:latest
    ports:
      -"9000:9000"
      -"9001:9001"
    volumes:
      - minio:/data
    networks:
      - bf-net
    environment:
      - MINIO_ROOT_USER=${MINIO_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_PASS}
      - MINIO_DEFAULT_BUCKETS=${MINIO_BUCKET}
networks:
  bf-net:
volumes:
  mysql:
  redis:
  minio:
  queue: